language:
    - java

services:
    - mysql

jdk:
    - oraclejdk7

before_install:
    - mysql -u root < init.sql

script:
    - cd Item\ 3/Acme-CnG/
    - mvn exec:java -Dexec.mainClass="utilities.PopulateDatabase"
    - mvn clean test
    - ls -lah

cache:
    directories:
        - $HOME/.m2   # Cache para las dependencias de maven

dist:
    - trusty

sudo:
    - false

notifications:
- email: false
